### ISSUE TITLE
Set up sftp inbox

### ISSUE THREAD

**Issue by viklund** [NBISweden/swefreq#369]
We need an inbox for people to upload data into:

 - User accounts should be managable by us somehow (no need for sysadmin).
   - In the future this will probably be managed somehow through the webinterface.
 - Uploads will be a handful of files probably less than 50Gb

Current Status

- [x] Firewall on `swefreq-proxy` on external interface redirects to port 2222
- [ ] Nginx redirects to `swefreq-sftp`
- [x] `swefreq-sftp` set up to use database on `swefreq-db`
   - [ ] Test locally with a user
- [ ] Merge `develop` branch into `master` to get credential generation UI.
